# Generated by Django 4.1.1 on 2023-05-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="address", name="area"),
        migrations.RemoveField(model_name="address", name="district"),
    ]
