# Generated by Django 4.1.1 on 2023-09-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_car_user_alter_chat_user_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(
                default="", upload_to="frontend/static/images/ad/%Y/%m/%d/"
            ),
        ),
    ]
