# Generated by Django 4.1.1 on 2023-04-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="price",
            field=models.IntegerField(),
        ),
    ]
