# Generated by Django 4.1.1 on 2023-09-27 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_car_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="carSellState",
        ),
    ]
