# Generated by Django 4.1.1 on 2023-04-19 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_user_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="image",
        ),
    ]
