# Generated by Django 4.1.1 on 2023-04-20 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_user_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="image",
        ),
    ]
