# Generated by Django 4.1.1 on 2023-04-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_car_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                default="",
                null=True,
                upload_to="frontend/static/images/ad/%Y/%m/%d/",
            ),
        ),
    ]
