# Generated by Django 4.1.1 on 2023-05-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.ImageField(default="", upload_to="image/images"),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(default="", upload_to="image/images"),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
