# Generated by Django 4.1.1 on 2023-05-07 05:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_car_image_alter_user_image_delete_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="image",
        ),
    ]
