# Generated by Django 4.1.1 on 2023-05-07 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_car_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="image",
        ),
    ]
