# Generated by Django 4.1.1 on 2023-05-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_remove_car_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.ImageField(default="", upload_to="image/images"),
        ),
    ]
