# Generated by Django 4.1.1 on 2023-05-10 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_car_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="image",
        ),
    ]
