# Generated by Django 4.1.1 on 2023-05-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_remove_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(default="", upload_to="image/images"),
        ),
    ]
