# Generated by Django 4.1.1 on 2023-05-11 19:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(default="", upload_to=api.models.upload_path),
        ),
    ]
