# Generated by Django 4.1.1 on 2023-05-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_remove_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(default="", upload_to="uploads/images"),
        ),
    ]
